server:
  port: 8443

  ssl:
    enabled: true
    key-store: classpath:gateway-keystore.p12
    key-store-password: password123
    key-store-type: PKCS12
    key-alias: gateway

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: bXlTdXBlclNlY3JldEtleUZvckp3dFNpZ25pbmcxMjM0NTY=
  expiration: 3600000

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO
