server:
  port: 8084

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer:
        org.apache.kafka.common.serialization.StringSerializer
      value-serializer:
        org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

      key-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer

      properties:
        spring.json.trusted.packages: "*"

        spring.json.use.type.headers: false

        spring.json.value.default.type:
          payment.app.notification_service.kafka.event.TransactionCompletedEvent

# Kafka secret
aes:
  secret: ${AES_SECRET}

# Kafka topic configuration
app:
  kafka:
    topics:
      transaction-completed: transaction-completed
      transaction-reversed: transaction-reversed
